version: '3.4'

services:
    localstack:
        image: localstack/localstack:0.11.2
        ports:
            - "4566:4566"
        environment:
            - SERVICES=sqs
            - AWS_ACCESS_KEY_ID=guest
            - AWS_SECRET_ACCESS_KEY=guest
            - AWS_DEFAULT_REGION=us-east-1

    postgres:
        image: postgres:12-alpine
        ports:
            - "15432:15432"
            - "5432:5432"
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "password"

    localstack-create-queues:
        image: amazon/aws-cli:2.0.28
        environment:
            - AWS_ACCESS_KEY_ID=guest
            - AWS_SECRET_ACCESS_KEY=guest
            - AWS_DEFAULT_REGION=us-east-1
        depends_on:
            - localstack
        links: ["localstack"]
        hostname: localstack-create-queues
        entrypoint: /bin/sh -c
        command: >
            "
                while ! aws --endpoint-url=http://localstack:4566 sqs list-queues > /dev/null; do echo waiting; sleep 3; done;
                aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name GetFromDataBaseMessageQueue.fifo --attributes FifoQueue=true
                aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name GetFromExternalApiMessageQueue.fifo --attributes FifoQueue=true
                aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name SendToQueueMessageQueue.fifo --attributes FifoQueue=true
                aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name SentToQueueMessageQueue.fifo --attributes FifoQueue=true
                aws --endpoint-url=http://localstack:4566 sqs list-queues
                echo 'SQS-DONE!' 
            "