// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Infrastructure.Persistance;

namespace WebApi.Infrastructure.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20211103061548_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WebApi.Application.Entities.OtherThing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_other_thing");

                    b.ToTable("other_thing");
                });

            modelBuilder.Entity("WebApi.Application.Entities.Something", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("OtherThingId")
                        .HasColumnType("uuid")
                        .HasColumnName("other_thing_id");

                    b.HasKey("Id")
                        .HasName("pk_somethings");

                    b.HasIndex("OtherThingId")
                        .HasDatabaseName("ix_somethings_other_thing_id");

                    b.ToTable("somethings");
                });

            modelBuilder.Entity("WebApi.Application.Entities.Something", b =>
                {
                    b.HasOne("WebApi.Application.Entities.OtherThing", "OtherThing")
                        .WithMany()
                        .HasForeignKey("OtherThingId")
                        .HasConstraintName("fk_somethings_other_thing_other_thing_id");

                    b.Navigation("OtherThing");
                });
#pragma warning restore 612, 618
        }
    }
}
