name: Herald.Template.WebApi

on:
  push:
    branches:
      - "master"

jobs:    
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - name: Build / Test
      run: | 
        dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput="../coverage.xml" -p:Thereshold=80

    - name: Publish Coverage
      run: | 
        curl -s https://codecov.io/bash > codecov
        chmod +x codecov
        ./codecov -f "coverage.xml" -t ${{ secrets.CODECOV_TOKEN }}